package:
  name: vulkanmitts
  version: "0.11"

source:
  git_url: https://gitlab.com/vlam3d/vulkanmitts.git

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - vulkanmitts

about:
  home: https://gitlab.com/vlam3d/vulkanmitts.git
  license: MIT License
  summary: "Khronos Vulkan API Python Bindings"
