package:
  name: vulkanmitts
  version: "0.9"

source:
  git_url: https://github.com/VLAM3D/vulkanmitts.git

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - vulkanmitts

about:
  home: https://github.com/VLAM3D/vulkanmitts
  license: MIT License
  summary: "Khronos Vulkan API Python Bindings"
