package:
  name: pyglslang
  version: "0.9"

source:
  git_url: https://github.com/VLAM3D/pyvulkan.git
  
requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - pyglslang

about:
  home: https://github.com/VLAM3D/pyvulkan
  license: MIT License
  summary: "Khronos Vulkan API Python Bindings"
