package:
  name: pyglslang
  version: "0.9"

source:
  git_url: https://github.com/VLAM3D/vulkanmitts.git

requirements:
  build:
    - python
    - numpy
    - swig
    - vs2015_runtime # [win]

  run:
    - python
    - numpy
    - swig
    - vs2015_runtime # [win]

test:
  # Python imports
  imports:
    - pyglslang
  requires:
    - contextlib2
  source_files:
    - test_pyglslang.py
    - glsl_to_spv.py
    - vertex_shader.glsl
    - fragment_shader.glsl
  commands:
    - python test_pyglslang.py

about:
  home: https://github.com/VLAM3D/vulkanmitts
  license: MIT License
  summary: "Khronos Vulkan API Python Bindings"
